version: "3.7"

networks:
  default:
    external: true
    name: cloudbuild
  odoonet:

volumes:
  odoo-data:
  odoo-testlogs:
  odoo-modules:
  psql:

services:
  odoo:
    image: iterativodo/dockerdoo:${ODOO_VERSION}
    env_file: .env

    restart: unless-stopped

    ports: ["80:8069", "8072:8072"]

    volumes:
      # Host paths (.ssh configuration)
      - ~/.ssh/:/opt/odoo/.ssh/:cached
      # Named volumes
      - ./custom:${ODOO_EXTRA_ADDONS}:delegated
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-testlogs:${ODOO_LOGS_DIR}
    depends_on:
      - db

    networks:
      odoonet:
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      odoonet:
